name: Deploy Go To Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4


      - name: 📦 Deploy to Server
        run: |
          cd /var/www/dimensy-bridge
          git config --global --add safe.directory /var/www/dimensy-bridge

          sudo git stash || true
          sudo git fetch
          sudo git checkout main
          sudo git pull origin main

          # build binaries
          sudo GOOS=linux GOARCH=amd64 go build -buildvcs=false -o dimensy-bridge ./cmd/server
          sudo GOOS=linux GOARCH=amd64 go build -buildvcs=false -o migrate ./cmd/migrate

          sudo chmod +x dimensy-bridge
          sudo chmod +x migrate
          sudo go mod tidy

          sudo ./migrate

          sudo systemctl restart dimensy-bridge
          sudo systemctl status dimensy-bridge --no-pager -l
